In [20]:
#LOAD LIBRARIES
import numpy as np
import seaborn as sb
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [21]:
#LOAD DATASET
data = sb.load_dataset('iris')

In [22]:
#SEE THE STRUCTURE OF DATASET
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [23]:
#GENERATE RANDOM INDICES FOR 90% OF ROWS
np.random.seed(40)
ran = np.random.choice(data.index, size = int(0.9 * len(data)), replace = False)
ran

array([ 38,  66, 115, 117,  89, 136,  68,  94,  84,  28,  90,  11,  40,
       126,  79, 144, 123, 124,  76,  59, 132, 105,  53,  17,  64,  18,
        13, 116,   9,  81,  62,  23,  26,  48,   2, 128,   6,  42, 113,
        15,   3,  86, 127, 102, 125,  39, 118, 138,  75,  37, 100,  54,
        67,  97,  24,  16,  96,  69, 111, 133,   4, 143,  61,  10, 112,
        45,  29, 122,  47, 129, 110,  20, 147,  51,  32,  21, 140,  27,
       137, 146,  77,  56, 145,  78, 135,  34, 101,  72,  52,  33,   1,
         0, 120, 142,  63,  36,  85, 103, 109,  57, 149, 119,  58,  83,
        25,  93,  88, 107,  95, 130,  41, 134, 148,  65,  80,   5, 108,
        82,  31,  98, 106,  35,  43, 121,  87,  46,  44,  60,  30, 141,
        99, 131,  22, 104,  92])

In [24]:
#EDA
print(data.info())
print(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [25]:
#NORMALIZATION USING MINMAXSCALER
s = MinMaxScaler()
data_norm = pd.DataFrame(s.fit_transform(data.iloc[: , 0:4]), columns = data.columns[0:4])

In [26]:
#SUMMARIES
print("\n Original Data Summary:")
print(data.describe())
print("\n\n\n")
print("\n Normalized Data Summary:")
print(data_norm.describe())

 Original Data Summary:
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000





 Normalized Data Summary:
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       0.428704     0.440556      0.467458     0.458056
std        0.230018     0.181611      0.299203     0.317599
min        0.000000     0.000000      0.000000     0.000000
25%        0.222222     0.333333      0.101695     0.083333
50%        0.416667     0.416667      0.567797     0.500000
75%        0.583333     0.541667      0.694915     0.708333
max        1.000000     1.000000      1.000000     1.000000

In [27]:
#EXTRACT TRAINING AND TESTING SETS
data_train = data_norm.iloc[ran, :]
data_test = data_norm.drop(ran)
data_target_cat = data.iloc[ran, 4]
data_test_cat = data.drop(ran)['species']

In [28]:
#RUN KNN
knn = KNeighborsClassifier(n_neighbors = 11)
knn.fit(data_train, data_target_cat)
pr = knn.predict(data_test)

In [29]:
#CONFUSION MATRIX
mat = confusion_matrix(data_test_cat, pr)
print("\n CONFUSION MATRIX\n")
mat

 CONFUSION MATRIX

array([[6, 0, 0],
       [0, 6, 1],
       [0, 0, 2]])

In [30]:
#CALCULATE ACCURACY
acc = accuracy_score(data_test_cat, pr) * 100
print("\n ACCURACY : {:.2f}%".format(acc))

 ACCURACY : 93.33%

In [31]:
#LOAD DATASET
df = sb.load_dataset('diamonds')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [32]:
#GENERATE RANDOM INDICES FOR 90% OF ROWS
np.random.seed(40)
rand = np.random.choice(df.index, size = int(0.9 * len(data)), replace = False)
rand

array([38807, 36031, 28575, 51189, 10962, 36989, 29237, 21954, 36294,
        3124, 32148, 33652, 41119, 26148, 36111,  2764, 28803, 47760,
       52677, 12739, 41326, 46823, 40037, 49920, 25642, 41320, 25613,
       35869, 32381, 32402, 36752, 50990, 40214, 17667, 46051, 34013,
       53566, 23970, 33981, 30704, 35641, 39282, 41169, 23260,  2004,
       48701,  7756, 39424, 24060, 34529, 50489, 28263, 34409, 19460,
       36788, 20051, 43076,  1875, 10834, 22601, 22704, 16782, 33877,
        5122, 30116, 21011, 25051,  7455,  9250, 34071, 10685,  7156,
       31066, 10851, 44312, 16569, 28594, 39274,  6821,  1248, 48672,
        4691, 16683,  8669,  6700, 28269, 41180, 22227,  6384, 33479,
       47966,  2808, 35606, 19669, 38129, 33607, 13246, 23409,   358,
       11676,  4056, 33835, 14699, 30018, 31701, 42271, 37228, 38045,
       29510, 12336, 46299, 17598,  8290, 25352, 13261, 23561,  3036,
       11730, 15905, 22863, 28769, 30593, 50449,  8917,  3059, 51667,
        7432, 33229, 43604, 29035, 47668,  8720, 46905, 24405, 43108])

In [42]:
#SEEDING
np.random.seed(40)
ran1 = np.random.choice(df.index, size = int(0.9 * len(df)), replace = False)

In [43]:
#DIFFER COLS
num_cols = ['carat', 'depth', 'table', 'price', 'x', 'y', 'z']

In [44]:
#NORMALIZATION OF DATA
df_norm = pd.DataFrame(s.fit_transform(df[num_cols]), columns=num_cols)

In [45]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [46]:
df_norm.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.124312,0.520817,0.278023,0.194994,0.533627,0.097360,0.111281
std,0.098547,0.039795,0.042971,0.215680,0.104447,0.019391,0.022192
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.041580,0.500000,0.250000,0.033735,0.438547,0.080136,0.091509
50%,0.103950,0.522222,0.269231,0.112180,0.530726,0.096944,0.111006
75%,0.174636,0.541667,0.307692,0.270219,0.608939,0.111036,0.127044
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [47]:
#EXTRACT TRAIN AND TEST DATASETS
df_train = df_norm.iloc[ran1, :]
data_test = df.drop(ran1)['cut']

In [ ]:
#RUN KNN